# Generated by Django 4.1.13 on 2024-12-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='department',
            new_name='Departamento',
        ),
    ]
