# Generated by Django 4.1.13 on 2024-12-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='empleado.habilidades'),
        ),
    ]
